# Generated by Django 3.2.5 on 2021-08-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('employee', 'employee')], default='user', max_length=10),
            preserve_default=False,
        ),
    ]
