# Generated by Django 3.2.5 on 2021-08-11 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=shop.models.company_logo_directory)),
            ],
            options={
                'verbose_name_plural': 'Компании',
                'db_table': 'company',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Корзина пользователя'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Добавленные в корзину пользователем продукты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Подкатегории товаров'},
        ),
        migrations.AddField(
            model_name='item',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.company_product_directory),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Работники компании',
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company'),
        ),
    ]
