# Generated by Django 3.2.5 on 2021-08-22 12:43

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210822_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.company_logo_directory),
        ),
        migrations.AddField(
            model_name='item',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.company_product_directory),
        ),
    ]
