# Generated by Django 3.2.5 on 2021-08-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210827_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_step_begin', models.DateField(null=True)),
                ('date_step_end', models.DateField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_step', models.CharField(default='Оплата', max_length=50)),
                ('orders', models.ManyToManyField(related_name='steps', through='shop.OrderStep', to='shop.Order')),
            ],
        ),
        migrations.AddField(
            model_name='orderstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.step'),
        ),
    ]
